// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230131121022_seedProducts")]
    partial class seedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "cyan",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=299964152",
                            Title = "Licensed Wooden Shoes"
                        },
                        new
                        {
                            Id = 2,
                            Color = "turquoise",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2123807840",
                            Title = "Sleek Concrete Tuna"
                        },
                        new
                        {
                            Id = 3,
                            Color = "tan",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=160184147",
                            Title = "Sleek Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Color = "teal",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=607508437",
                            Title = "Ergonomic Fresh Cheese"
                        },
                        new
                        {
                            Id = 5,
                            Color = "orange",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1073771022",
                            Title = "Handcrafted Metal Computer"
                        },
                        new
                        {
                            Id = 6,
                            Color = "salmon",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1313793306",
                            Title = "Small Cotton Hat"
                        },
                        new
                        {
                            Id = 7,
                            Color = "purple",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=783199101",
                            Title = "Fantastic Plastic Pants"
                        },
                        new
                        {
                            Id = 8,
                            Color = "magenta",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=388427480",
                            Title = "Unbranded Concrete Hat"
                        },
                        new
                        {
                            Id = 9,
                            Color = "ivory",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1693823615",
                            Title = "Gorgeous Frozen Chair"
                        },
                        new
                        {
                            Id = 10,
                            Color = "blue",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1289193751",
                            Title = "Incredible Cotton Chips"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
