// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230131121300_seedProducts2")]
    partial class seedProducts2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            Color = "maroon",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1169386606",
                            Title = "Practical Soft Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Color = "azure",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=143765656",
                            Title = "Incredible Granite Chair"
                        },
                        new
                        {
                            Id = 33,
                            Color = "purple",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1838222584",
                            Title = "Awesome Fresh Fish"
                        },
                        new
                        {
                            Id = 34,
                            Color = "turquoise",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=131869673",
                            Title = "Intelligent Wooden Computer"
                        },
                        new
                        {
                            Id = 35,
                            Color = "black",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=49825613",
                            Title = "Incredible Frozen Car"
                        },
                        new
                        {
                            Id = 36,
                            Color = "salmon",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1353590140",
                            Title = "Generic Cotton Cheese"
                        },
                        new
                        {
                            Id = 37,
                            Color = "pink",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1137660981",
                            Title = "Fantastic Plastic Shoes"
                        },
                        new
                        {
                            Id = 38,
                            Color = "silver",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2036824952",
                            Title = "Practical Metal Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Color = "lavender",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2061613799",
                            Title = "Rustic Soft Shoes"
                        },
                        new
                        {
                            Id = 40,
                            Color = "orange",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=256177860",
                            Title = "Intelligent Concrete Sausages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
